server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://192.168.0.173:5432/customer
    properties:
      serverTimezone: Europe/Budapest
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
      show-sql: 'true'