server:
  port: 8081
spring:
  application:
    fraud
  datasource:
    url: jdbc:postgresql://192.168.0.173:5432/fraud
    properties:
      serverTimezone: Europe/Budapest
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
      show-sql: 'true'